### ISSUE TITLE
The argument 'path' must be a string or Uint8Array without null bytes.

### ISSUE THREAD

**Issue by merceyz** [vitejs/vite-plugin-vue2#63]
When running `vite build` it fails with the following error

```console
$ yarn vite build
vite v3.2.2 building for production...
✓ 46 modules transformed.
[vite:vue2] Could not load /vite-vue2-null-repro/node_modules/vue2-google-maps/dist/components/placeInputImpl.js?vue&type=script&src=true&lang.js?commonjs-exports (imported by node_modules/vue2-google-maps/dist/components/placeInputImpl.js?vue&type=script&src=true&lang.js): The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00/vite-vue2-null-repro/node_modules/vue2-google-maps/dist/components/placeInputImpl.js'
error during build:
TypeError [PLUGIN_ERROR]: Could not load /vite-vue2-null-repro/node_modules/vue2-google-maps/dist/components/placeInputImpl.js?vue&type=script&src=true&lang.js?commonjs-exports (imported by node_modules/vue2-google-maps/dist/components/placeInputImpl.js?vue&type=script&src=true&lang.js): The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00/vite-vue2-null-repro/node_modules/vue2-google-maps/dist/components/placeInputImpl.js'
    at Object.openSync (node:fs:586:10)
    at Object.readFileSync (node:fs:462:35)
    at Object.load (/vite-vue2-null-repro/node_modules/@vitejs/plugin-vue2/dist/index.cjs:3217:30)
    at file:///vite-vue2-null-repro/node_modules/rollup/dist/es/shared/rollup.js:22748:40
```

# To reproduce

```sh
git clone https://github.com/merceyz/vite-vue2-null-repro
cd vite-vue2-null-repro
yarn
yarn vite build
```

# Environment

```
System:
  OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
Binaries:
  Node: 16.18.0 - /tmp/xfs-46b3435e/node
  Yarn: 3.2.4 - /tmp/xfs-46b3435e/yarn
```

# Extra

This is the same issue as https://github.com/vitejs/vite-plugin-vue2/issues/31

**Comment by hzuluaga** [comment]
I have the same issue , did you solve it ?

**Comment by arjen-mediasoep** [comment]
@merceyz @hzuluaga I'm having the same issue. Did one of you solve this?

**Comment by RyanGst** [comment]
same here

**Comment by prosohail51214** [comment]
I am having same issue, anyone found solution?

**Comment by prosohail51214** [comment]
Hi, I fixed this issue by modifying node_modules/vue2-google-maps/components/placeInput.vue file.

All you have to do is just replace 
<script src="./placeInputImpl">
</script>

with

<script>
export default (function (x) { return x.default || x })(require('./placeInputImpl.js'))
</script>

**Comment by aroy314** [comment]
If this is a working solution, could this be fixed on the packge with a merge request please ? 
This way we don't have to manually change it after each npm install or update ;) 
Thanks !

**Comment by aroy314** [comment]
Solution for those who still have the problem : 
1. Create a file modifyPlaceInput.js
```
const fs = require('fs')
const path = require('path')

// this file exists because the plugin vue2-google-maps does not support vite
// https://github.com/vitejs/vite-plugin-vue2/issues/63#issuecomment-1946669520

const filePath = path.join(__dirname, 'node_modules/vue2-google-maps/dist/components/placeInput.vue')

// Read the file
fs.readFile(filePath, 'utf8', (err, data) => {
	if (err) {
		console.error('Error reading file:', err)
		return
	}

	// Check if needle is foudable (not already modified)
	if (!data.includes('<script src="./placeInputImpl.js">')) {
		console.log('File already modified')
		return
	}

	// Replace the desired content
	const modifiedData = data.replace(
		'<script src="./placeInputImpl.js">',
		'<script> export default (function (x) { return x.default || x })(require(\'./placeInputImpl.js\'))'
	)

	// Write the modified content back to the file
	fs.writeFile(filePath, modifiedData, 'utf8', (err) => {
		if (err) {
			console.error('Error writing file:', err)
		} else {
			console.log(`File modified successfully in ${filePath}\n`)
		}
	})
})
```
2. run the script before launching compilation : `node modifyPlaceInput.js && vite build`

**Comment by aroy314** [comment]
@adriandmitroca this file should be only executed by node (see my point n°2), so vite has no idea this exists unless you imported it in your project by mistake. On my end it fixed the issue.
